en:
  rules:
    distance:
      origin:
        size?: must be have a size between 1..60

      destination:
        size?: must be have a size between 1..60

      kilometers:
        gteq?: must be greater than or equal 0
        lteq?: must be less than or equal 100000
